### PR TITLE
Latest version of Nginx

### PR DESCRIPTION
**Pull request by NohaTech**
Added information how to update/install latest stable version of Nginx as that are important to have the latest version.

### CODE REVIEW

**Comment by shoeper** [comment]
I disagree with this. In most cases it is enough to use the version that comes with the system.

**Comment by Calby1988** [comment]
Well, from version 1.10 to 1.12 it's many bug and security fixes so I can't really agree with you.
Take a look at the change log from NGINX.

http://nginx.org/en/CHANGES

**Comment by shoeper** [comment]
Security fixes are being applied for older versions for any serious Linux operating system.

**Comment by shoeper** [comment]
I think this one can be closed.

**Pull request closed without merging**
