### PR TITLE
ENABLE_REPO_HISTORY_SETTING

### PR DESCRIPTION
**Pull request by shoeper**

### CODE REVIEW

**Comment by shoeper** [comment]
@freeplant are all options from https://github.com/haiwen/seahub/blob/7cb20817bb02293262deb615c06c7c0c2e0025db/seahub/settings.py already available?

e.g.
```
# Common settings(file extension, storage) for avatar and group avatar.
AVATAR_FILE_STORAGE = '' # Replace with 'seahub.base.database_storage.DatabaseStorage' if save avatar files to database
AVATAR_ALLOWED_FILE_EXTS = ('.jpg', '.png', '.jpeg', '.gif')
# Avatar
AVATAR_STORAGE_DIR = 'avatars'
AVATAR_HASH_USERDIRNAMES = True
AVATAR_HASH_FILENAMES = True
AVATAR_GRAVATAR_BACKUP = False
AVATAR_DEFAULT_URL = '/avatars/default.png'
AVATAR_DEFAULT_NON_REGISTERED_URL = '/avatars/default-non-register.jpg'
AVATAR_MAX_AVATARS_PER_USER = 1
AVATAR_CACHE_TIMEOUT = 14 * 24 * 60 * 60
AUTO_GENERATE_AVATAR_SIZES = (16, 20, 24, 28, 32, 36, 40, 48, 60, 80, 290)
```

But there are even more undocumented options. Think they should all get documented.

**Comment by freeplant** [comment]
These options are for internal usage only. Though they can be overwritten in seahub_settings.py. It is better not to do so.

**Comment by shoeper** [comment]
Ok, I understand, but I think it would be helpful if they are mentioned. Maybe we could introduce a new section at the buttom of the page. Espacially for larger setups it could be helpful to know them. 
Of course admins can also have a look at the source but having a full documentation could save some hassle.

**Comment by freeplant** [comment]
Because undocumented options are only used internally, they can be changed/removed without notice. Documenting and using them is not a good way for admins.

**Comment by shoeper** [comment]
Thanks for explanation.

**Pull request merged**
