### PR TITLE
Fix SqliteToMysql migration + support for all versions

### PR DESCRIPTION
**Pull request by Lonsarg**
Based on fixes I published in this forum post: https://forum.seafile.com/t/a-few-sql-errors-during-migration-from-sqlite-to-mysql/8877/8

1. The main script is fixed, it did not handle certain table names properly (I added ´´ around table name to fix it). 
2. Additionally due to schema changes existing *db.sql files worked only for 6.0 and 6.1. I have now created files for 6.3 from a fresh mysql installation and also updated manual to make this clear (originally manual never mentioned that it was version specific, but it was).
3. To be more future proof I have added optional steps into manual on how to manually generate needed .sql files yourself, meaning if you have any other version than 6.3 you can still migrate with this extra steps
4. I also removed some obsolete notes from manual that are not relevant for some time now (updates to the script that I made years ago remove all dependencies on python for example, it is pure .sh now).

While the scripts and .sql files were tested by me and additionally by f.damien12 on forum what I have not tested is the manual, I made blind changes in notepad since I don't know how to open .md files. So someone should check the look and download links in this changed file:
migrate_from_sqlite_to_mysql.md

### CODE REVIEW

**Comment by Lonsarg** [comment]
@renfeipeng , 11 days ago you seem to have returned this migration guide/script to 3+ years old version with python and manual hacks on data after migration (that are by very nature version dependent), this caused many issues in the past. Schema on migrated MySQL is not the same as with fresh MySQL if migrated this way, which is a no-go and can cause very devastating problems if someone migrates this way (even if successfully), data loss is very likely with this approach. 

Of course the "11 days ago script" also had some problems with latest versions, but only small fixes were necessary which I made in this pull request, maybe it went unnoticed?

**Comment by kevinxw** [comment]
@Lonsarg your script doesn't work for me. It's saying
"Error: mode should be one of: ascii column csv html insert line list quote tabs tcl"
to me.
You should change to the following code to have better compatibility 

`
         #generate insertstatemets (via echoMultipleCommands support by sqlite3), does not include column names
         sqlite3 "$1" ".mode insert a_table_name_will_not_conflict" "select * from '${TABLE}';" |

         #replace 3rd word with columns from above and also add ``:  `TableName`(`col1`, `col2`, `col3`, ...)
         sed "s/a_table_name_will_not_conflict/\`${TABLE}\` (${COLS_PURE})/g"
`

**Comment by kevinxw** [comment]
I am pasting my modified version of the migration script in case anyone need it.
I have used it on 7.0.2 and works for me
https://gist.github.com/kevinxw/aaf88505e0297d70a01eef26925e6025

**Comment by Lonsarg** [comment]
kevinxw your fixes work great. They apperently really remove issues with distro compatibility, you have also made some other improvements i see. I have tested your fixed sqlite_to_mysql.sh script and it also works for my test 6.4.3. installation i have on Ubuntu. 

I have updated this pull request with your version.

I have not included your aditional migration.sql script at the moment since i do not find the referenced paths "seafile-server-latest/sql/mysql/ccnet.sql" and "seafile-server-latest/sql/mysql/seafile.sql" in my 6.4.3 installation, this is something new on Version 7.x maybe? Will look into it later, we can make manual even less complited if they are included by default in installation.

**Comment by Lonsarg** [comment]
Seems this repo is not maintained, so closing.

**Pull request closed without merging**
