### PR TITLE
Feature suggestion for #178

### PR DESCRIPTION
**Pull request by darkcircle**
I told my idea in #178 to improve document and translation maintenance efficiency.

and this is my simple code to resolve.

### CODE REVIEW

**Comment by darkcircle** [comment]
if you want to see result example w/o broken, you can install Korean font by

```sudo apt-get install fonts-noto-cjk```

**Comment by darkcircle** [comment]
and It's ABSOLUTELY NOT for merge :)

**Comment by felag** [comment]
Hello Darkcircle,
first of all: thanks for you suggestion !

I have cloned your master branch in a [translation branch in my repo](https://github.com/felag/seafile-docs/tree/translation). I have made minor commits to use python3 even when python 2.x is installed.
I have also updated README.md file to add a translation paragraph.

**Comment by darkcircle** [comment]
Thank you for helping me!
Here is missing comment(sorry to late).

1. Translator credit should be written on the header description in po file( refer my example ;) ).
2. Copyright description should follow as
"# This file is distributed under the same license as the seafile-docs package."
3. Last-translator:, Language-team:, Language: should be filled. If there is no Language-team:, write as Coordinator-name <name@email.to> (currently, Language-team checking code is missing)
4. Plural-Forms: does not have to be filled. there is no plural variable.

you can run update.sh to update pot, and compile.sh to compile po to generate translated document.
both script should be run on the root path of seafile-docs.

Enjoy! :D

**Comment by darkcircle** [comment]
if you updated your code by pulling source tree from my fork,
you would better to run just at once ./update.sh on the root path of seafile-docs

**Comment by darkcircle** [comment]
closing.
This pr is old and should be replaced to #192

**Pull request closed without merging**
