### PR TITLE
Update webdav.md with nginx timeout settings

### PR DESCRIPTION
**Pull request by DerDanilo**
Added nginx timeout settings

### CODE REVIEW

**Comment by freeplant** [comment]
Thank you.

**Comment by shoeper** [comment]
There are multiple problems with this change.

 * proxy_request_buffering off; is doubled
 * proxy_* does not has any effects on fcgi_ so correct would be to use timeouts from http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html instead.

**Comment by DerDanilo** [comment]
Kannst du das dann bitte korrigieren? Bisher hatte ich mit der Konfig keine Probleme. Läuft ein mehreren Servern seit Monaten. :) - Danke!

**Comment by DerDanilo** [comment]
We need someone to point out about NGINX and proxy_.... used those settings quiet a while and it seems to work fine.

**Pull request merged**
